"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExchangeAuthorization = void 0;
var mongoose_1 = require("mongoose");
var ExchangeAuthorization_model_1 = require("./ExchangeAuthorization.model");
var statics_1 = require("./statics");
var methods_1 = require("./methods");
(0, methods_1.methods)(ExchangeAuthorization_model_1.exchangeAuthorizationSchema);
(0, statics_1.statics)(ExchangeAuthorization_model_1.exchangeAuthorizationSchema);
exports.ExchangeAuthorization = (0, mongoose_1.model)("ExchangeAuthorization", ExchangeAuthorization_model_1.exchangeAuthorizationSchema);
