name: Node.js Package

on:
  release:
    types: [create]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@visionsofficial"
      # Setup pnpm since we're using a pnpm-lock file
      - name: Setup pnpm
        run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - name: Check token
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
